report_bcsm_path: "/bcsm"
apply_charging_path: "/applyCharging"
specialized_resource_path: "/specializedResource"
dialog_error_path: "/dialogError"
error_component_path: "/errorComponent"
# the settings above are ignored in current version
call_state_changed_path: "/callStateChanged"
resource_completed_path: "/resourceCompleted"
call_aborted_path: "/callAborted"
call_fault_detected_path: "/callFaultDetected"
call_ended_path: "/callEnded"
http_connection_timeout_ms: 20000
service_response_timeout_ms: 3000
http_max_total: 10000
http_max_per_route: 1000
update_auto_statistic_period_ms: 1000
reset_statistic_period_ms: 0
write_statistic_period_ms: 60000
# Important!!! This parameter should be less or equal than DialogIdleTimeout specified in TcapStackCap_management.xml or TcapStack_management.xml
invoke_timeout_ms: 30000
reset_call_timeout_ms: 500
reset_call_limit: 5
rules_update_period_sec: 60
abstract_thread_pool_size: 7
rule_service_thread_pool_size: 10
reset_timer_service_thread_pool_size: 10
use_translation: true
max_translation_apply_count: 5
msisdn_length_to_prefix: 11
secret_key: "${http.secret.key}"
#Используется только для INAP звонков с пустым EventTypeBCSM
empty_event_type_bcsm: "termAttemptAuthorized"
override_local_sccp_address: false
new_local_sccp_gt: 79031231234
